apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/component: logging
    app.kubernetes.io/instance: loki
    app.kubernetes.io/name: loki
    app.kubernetes.io/part-of: loki
    app.kubernetes.io/version: 2.7.0
  name: loki
  namespace: logging
spec:
  clusterIP: None
  ports:
  - name: grpc
    port: 9095
    protocol: TCP
    targetPort: grpc
  - name: http
    port: 80
    protocol: TCP
    targetPort: http
  publishNotReadyAddresses: true
  selector:
    app.kubernetes.io/component: logging
    app.kubernetes.io/instance: loki
    app.kubernetes.io/part-of: loki
