apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/component: message-queue
    app.kubernetes.io/instance: nats
    app.kubernetes.io/name: nats
    app.kubernetes.io/version: 2.8.4
  name: nats
  namespace: nats
spec:
  clusterIP: None
  ports:
  - name: client
    port: 4222
  - name: cluster
    port: 6222
  - name: leafnodes
    port: 7422
  - name: metrics
    port: 7777
  - name: monitor
    port: 8222
  selector:
    app.kubernetes.io/component: message-queue
    app.kubernetes.io/instance: nats
    app.kubernetes.io/name: nats
