apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/component: message-queue
    app.kubernetes.io/instance: nats
    app.kubernetes.io/name: nats
    app.kubernetes.io/version: 2.8.4
  name: nats
  namespace: nats
