apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: nats
  namespace: nats
spec:
  endpoints:
  - port: monitor
  selector:
    matchLabels:
      app.kubernetes.io/component: message-queue
      app.kubernetes.io/instance: nats
      app.kubernetes.io/name: nats
      app.kubernetes.io/version: 2.8.4
