apiVersion: v1
data:
  nats.conf: |
    pid_file: "/var/run/nats/nats.pid"

    http: 8222

    cluster: {
      port: 6222

      routes: [ nats://nats-0.nats.nats.svc:6222 nats://nats-1.nats.nats.svc:6222 nats://nats-2.nats.nats.svc:6222 ],

      cluster_advertise: $CLUSTER_ADVERTISE
      connect_retries: 30
    }

    leafnodes {
      port: 7422
    }
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/component: message-queue
    app.kubernetes.io/instance: nats
    app.kubernetes.io/name: nats
    app.kubernetes.io/version: 2.8.4
  name: nats
  namespace: nats
