apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: redis-operator
  namespace: redis-operator
spec:
  endpoints:
  - port: metrics
  namespaceSelector:
    matchNames:
    - redis-operator
  selector:
    matchLabels:
      app.kubernetes.io/component: controller
      app.kubernetes.io/instance: redis-operator
      app.kubernetes.io/name: redis-operator
