apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/component: controller
    app.kubernetes.io/instance: redis-operator
    app.kubernetes.io/name: redis-operator
    app.kubernetes.io/version: v1.1.1
  name: redis-operator
  namespace: redis-operator
spec:
  ports:
  - name: metrics
    port: 9710
  selector:
    app.kubernetes.io/component: controller
    app.kubernetes.io/instance: redis-operator
    app.kubernetes.io/name: redis-operator
