apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/component: controller
    app.kubernetes.io/instance: redis-operator
    app.kubernetes.io/name: redis-operator
    app.kubernetes.io/version: v1.1.1
  name: redis-operator
  namespace: redis-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: controller
      app.kubernetes.io/instance: redis-operator
      app.kubernetes.io/name: redis-operator
  strategy:
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/component: controller
        app.kubernetes.io/instance: redis-operator
        app.kubernetes.io/name: redis-operator
        app.kubernetes.io/version: v1.1.1
    spec:
      containers:
      - image: quay.io/spotahome/redis-operator:v1.1.1
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 6
          initialDelaySeconds: 30
          periodSeconds: 5
          successThreshold: 1
          tcpSocket:
            port: 9710
          timeoutSeconds: 5
        name: controller
        ports:
        - containerPort: 9710
          name: metrics
          protocol: TCP
        readinessProbe:
          initialDelaySeconds: 10
          periodSeconds: 3
          tcpSocket:
            port: 9710
          timeoutSeconds: 3
        resources:
          limits:
            cpu: 100m
            memory: 90Mi
          requests:
            cpu: 10m
            memory: 50Mi
        securityContext:
          readOnlyRootFilesystem: true
          runAsNonRoot: true
          runAsUser: 1000
      restartPolicy: Always
      serviceAccountName: redis-operator
