apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/component: redis
    app.kubernetes.io/instance: redis
    app.kubernetes.io/name: redis
    app.kubernetes.io/version: 7.0.2
  name: redis
  namespace: redis
spec:
  ports:
  - name: metrics
    port: 9121
  - name: redis
    port: 6379
  selector:
    app.kubernetes.io/component: redis
    app.kubernetes.io/instance: redis
    app.kubernetes.io/name: redis
