apiVersion: apps/v1
kind: StatefulSet
metadata:
  annotations:
    config_hash: 2b0ccf512a9cfc7d87970b9eecdfc7b1
  labels:
    app.kubernetes.io/component: logging
    app.kubernetes.io/instance: loki
    app.kubernetes.io/name: loki-read
    app.kubernetes.io/part-of: loki
    app.kubernetes.io/version: 2.6.0
  name: loki-read
  namespace: logging
spec:
  persistentVolumeClaimRetentionPolicy:
    whenDeleted: Delete
    whenScaled: Delete
  podManagementPolicy: Parallel
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: logging
      app.kubernetes.io/instance: loki
      app.kubernetes.io/name: loki-read
      app.kubernetes.io/part-of: loki
  serviceName: loki-read
  template:
    metadata:
      annotations:
        config_hash: 2b0ccf512a9cfc7d87970b9eecdfc7b1
      labels:
        app.kubernetes.io/component: logging
        app.kubernetes.io/instance: loki
        app.kubernetes.io/name: loki-read
        app.kubernetes.io/part-of: loki
        app.kubernetes.io/version: 2.6.0
    spec:
      containers:
      - args:
        - -target=read
        - -config.file=/etc/loki/config.yaml
        image: grafana/loki:2.6.0
        imagePullPolicy: IfNotPresent
        name: read
        ports:
        - containerPort: 9095
          name: grpc
        - containerPort: 3100
          name: http
        - containerPort: 7946
          name: memberlist
        readinessProbe:
          httpGet:
            path: /ready
            port: 3100
          initialDelaySeconds: 15
          timeoutSeconds: 1
        resources:
          requests:
            cpu: 100m
            memory: 90Mi
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          readOnlyRootFilesystem: true
        volumeMounts:
        - mountPath: /data
          name: loki-read
        - mountPath: /etc/loki
          name: config
      securityContext:
        fsGroup: 10001
        runAsGroup: 10001
        runAsNonRoot: true
        runAsUser: 10001
      serviceAccountName: loki-read
      terminationGracePeriodSeconds: 4800
      volumes:
      - configMap:
          name: loki
        name: config
  volumeClaimTemplates:
  - metadata:
      labels:
        app.kubernetes.io/component: logging
        app.kubernetes.io/instance: loki
        app.kubernetes.io/name: loki-read
        app.kubernetes.io/part-of: loki
        app.kubernetes.io/version: 2.6.0
      name: loki-read
      namespace: logging
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 10Gi
